DROP TABLE IF EXISTS `artists_account`;
CREATE TABLE `artists_account` (
  `ARTIST_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(256) COLLATE utf8_bin NOT NULL UNIQUE,
  `PERSONA` varchar(32) COLLATE utf8_bin NOT NULL UNIQUE,
  `NICK` varchar(32) COLLATE utf8_bin NOT NULL UNIQUE,
  `STATUS` smallint(6) NOT NULL,
  `REGISTRATION_SOURCE` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `EMAIL_STATUS` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`ARTIST_ID`),
  KEY `ARTIST_ACCOUNT_EMAIL_IDX` (`EMAIL`(255)),
  KEY `ARTIST_ACCOUNT_PERSONA_IDX` (`PERSONA`(32)),
  KEY `ARTIST_ACCOUNT_NICK_IDX` (`NICK`(32))
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

