DROP TABLE IF EXISTS `user_wallet`;
CREATE TABLE `user_wallet` (
  `USER_ID` bigint(20) NOT NULL,
  `REPUTATION` int NOT NULL DEFAULT 0,
  `GOLD` int NOT NULL DEFAULT 0,
  `CRYSTAL` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;